POE/Controllers/GraphController.cs
using DbManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Modules;
using Newtonsoft.Json;
using POE.Models;
using Controller = Microsoft.AspNetCore.Mvc.Controller;

namespace POE.Controllers
{
    public class GraphController : Controller
    {
        private readonly Prog6212P2Context _context;

        public GraphController(Prog6212P2Context context)
        {
            _context = context;
            
        }

        public IActionResult Index()
        {
            //Get the user's id
            int userID = HttpContext.Session.GetInt32("UserID").Value;
            ViewData["UserID"] = userID;
            //Get a list of all the users modules, the self study hours and the hours they already studied
            var moduleEntries = from m in _context.Modules
                                join me in _context.ModuleEntries on m.ModuleId equals me.ModuleId
                                where me.UserId == userID
                                select new
                                {
                                    m.ModuleCode,
                                    m.SelfStudyHours,
                                    me.HoursStudied
                                };
            //populate the combobox so they can filter which module they want to see
            PopulateCombobox();
            
            var data = moduleEntries.ToList();
            //if there is no data, return the no modules page
            if (data == null || data.Count == 0)
            {
                return RedirectToAction("NoModules", "Modules");
            }
            else
            {
                //Create a list for all the data points
                List<DataPoint> dataPoints = new List<DataPoint>();

                //add each module to the list
                foreach (var module in data)
                {
                    //convert the long to a decimal
                    decimal selfStudy = (decimal)TimeSpan.FromTicks(module.SelfStudyHours).TotalHours;
                    decimal actHours = (decimal)TimeSpan.FromTicks(module.HoursStudied).TotalHours;
                    dataPoints.Add(new DataPoint("Actual Hours " + module.ModuleCode, actHours));
                    dataPoints.Add(new DataPoint("Ideal Hours " + module.ModuleCode, selfStudy));
                }

                //add the list to the viewbag
                ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
                return View();
            }
        }

        [HttpPost]
        public IActionResult Index([Bind("ModCode")] DataPoint mod)
        {
            ModuleManagement moduleManagement = new ModuleManagement();
            int userID = HttpContext.Session.GetInt32("UserID").Value;
            ViewData["UserID"] = userID;

            //get the module data for the specific module the user wants
            var moduleEntries = from m in _context.Modules
                                join me in _context.ModuleEntries on m.ModuleId equals me.ModuleId
                                where me.UserId == userID && m.ModuleCode == mod.ModCode
                                select new
                                {
                                    m.ModuleCode,
                                    m.SelfStudyHours,
                                    me.HoursStudied
                                };
            PopulateCombobox();
            var data = moduleEntries.ToList();
            if (data == null)
            {
                return RedirectToAction("NoModules", "Modules");
            }
            else
            {
               
                List<DataPoint> dataPoints = new List<DataPoint>();

                foreach (var module in data)
                {
                    decimal selfStudy = (decimal)TimeSpan.FromTicks(module.SelfStudyHours).TotalHours;
                    decimal actHours = (decimal)TimeSpan.FromTicks(module.HoursStudied).TotalHours;
                    dataPoints.Add(new DataPoint("Actual Hours " + module.ModuleCode, actHours));
                    dataPoints.Add(new DataPoint("Ideal Hours " + module.ModuleCode, selfStudy));
                }


                ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
                return View();
            }


        }

        public void PopulateCombobox()
        {
            int userID = HttpContext.Session.GetInt32("UserID").Value;
            //populate the combobox so the user cna filter which module they want to see
            var moduleEntries = from m in _context.Modules
                                join me in _context.ModuleEntries on m.ModuleId equals me.ModuleId
                                where me.UserId == userID
                                select new
                                {
                                    m.ModuleCode,
                                    m.SelfStudyHours,
                                    me.HoursStudied
                                };

            ViewData["Modules"] = new SelectList(moduleEntries, "ModuleCode", "ModuleCode");
        }

    }
}

POE/Controllers/StudySessionsController.cs
using DbManagement;
using DbManagement.Models;
using Microsoft.AspNetCore.Connections.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Modules;
using BindAttribute = Microsoft.AspNetCore.Mvc.BindAttribute;
using Controller = Microsoft.AspNetCore.Mvc.Controller;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;
using SelectList = Microsoft.AspNetCore.Mvc.Rendering.SelectList;
using ValidateAntiForgeryTokenAttribute = Microsoft.AspNetCore.Mvc.ValidateAntiForgeryTokenAttribute;

namespace POE.Controllers
{
    public class StudySessionsController : Controller
    {
        private readonly Prog6212P2Context _context;

        public StudySessionsController(Prog6212P2Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {

            int userID = HttpContext.Session.GetInt32("UserID").Value;

            //get all the user's study sessions
            var sessions = from s in _context.StudySessions
                           where s.UserId == userID
                           select new DGSession
                           {
                               ModuleCode = s.ModuleCode,
                               TimeStudied = TimeSpan.FromTicks(s.HoursStudied),
                               DateStudied = s.DateStudied
                           };
            ViewData["Sessions"] = await sessions.ToListAsync();
            if (sessions == null || !sessions.Any())
            {
                return RedirectToAction("NoModules", "Modules");
            }
            else
            {
                //populate the filter dropdown
                PopulateFindCombobox();
                return View();
            }
            
        }

        [HttpPost]
        public async Task<IActionResult> Index([Bind("ModCode")] DGSession session)
        {        
            //get the filter the user wants
            string code = session.ModCode;
            int userID = HttpContext.Session.GetInt32("UserID").Value;

            //get the sessions for those specific modules
            var sessions = from s in _context.StudySessions
                           where s.ModuleCode == code && s.UserId == userID
                           select new DGSession
                           {
                               ModuleCode = s.ModuleCode,
                               TimeStudied = TimeSpan.FromTicks(s.HoursStudied),
                               DateStudied = s.DateStudied
                           };
            ViewData["Sessions"] = await sessions.ToListAsync();
            //if there are no sessions for that module, return the no modules page
            if (sessions == null || sessions.Count() == 0)
            {
                return RedirectToAction("NoModules", "Modules");
            }
            else
            {
                //populate the filter dropdown
                PopulateFindCombobox();
                return View();
            }
        }

        // GET: StudySessions/Create
        public IActionResult Create()
        {
            ModuleManagement module = new ModuleManagement();
            //get the user's modules
            List<ModuleEntry> mods = module.GetModules(HttpContext.Session.GetInt32("UserID").Value);
            if (mods.Count() == 0 || mods == null)
            {
                return RedirectToAction("NoModules", "Modules");
            }
            else
            {
                //populate the module dropdown
                PopulateStudySessionComboBox();
                return View();
            }
            
        }

        // POST: StudySessions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ModuleCode,HoursStudied,DateStudied")] StudySessionHtmlModel studySession)
        {
            ViewData["UserID"] = HttpContext.Session.GetInt32("UserID").Value;
            if (ModelState.IsValid)
            {
                StudySessionManagement moduleManagement = new StudySessionManagement();
                //convertt the html module to the study session module
                await moduleManagement.ConvertStudySession(studySession, HttpContext.Session.GetInt32("UserID").Value);
                return RedirectToAction("Index", "Modules");
            }
            //populate the module dropdown
            PopulateStudySessionComboBox();
            return View(studySession);
        }

        public void PopulateFindCombobox()
        {
            ViewData["UserID"] = HttpContext.Session.GetInt32("UserID").Value;
            int userID = HttpContext.Session.GetInt32("UserID").Value;
            //get all the user's modules
            var prog6212P2Context = (from m in _context.Modules
                          join me in _context.ModuleEntries on m.ModuleId equals me.ModuleId
                          join ss in _context.StudySessions on m.ModuleCode equals ss.ModuleCode
                          where me.UserId == userID && ss.UserId == userID
                          select new
                          {
                              m.ModuleCode
                          }).Distinct();

            ViewData["Modules"] = new SelectList(prog6212P2Context, "ModuleCode", "ModuleCode");
        }

        public void PopulateStudySessionComboBox()
        {
            ViewData["UserID"] = HttpContext.Session.GetInt32("UserID").Value;
            int userID = HttpContext.Session.GetInt32("UserID").Value;
            //get all the user's modules that they have a study session for
            var prog6212P2Context = from m in _context.Modules
                                    join me in _context.ModuleEntries on m.ModuleId equals me.ModuleId
                                    where me.UserId == userID
                                    select m;
            ViewData["AddStudySession"] = new SelectList(prog6212P2Context, "ModuleCode", "ModuleCode");
        }


        public async Task<IActionResult> SessionsRequired(string sortOrder)
        {
            ViewData["UserID"] = HttpContext.Session.GetInt32("UserID").Value;
            int userID = HttpContext.Session.GetInt32("UserID").Value;

            //get the user's modules along with the hours they studied
            var modules = (from m in _context.Modules
                          join me in _context.ModuleEntries on m.ModuleId equals me.ModuleId
                          where me.UserId == userID
                          orderby m.ModuleCode
                          select new DGModule
                          {
                              ModuleCode = m.ModuleCode,
                              SelfStudyHours = TimeSpan.FromTicks(m.SelfStudyHours),
                              HoursStudied = TimeSpan.FromTicks(me.HoursStudied),
                              HoursLeft = TimeSpan.FromTicks(me.HoursLeft)
                          }).AsEnumerable();
            
            if (modules == null || modules.Count() == 0)
            {
                return RedirectToAction("NoModules", "Modules");
            }
            else
            {
                //Order the data according to what the user clicks
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                ViewBag.SelfHoursParm = sortOrder == "Self" ? "self_desc" : "Self";
                ViewBag.StudiedParm = sortOrder == "Studied" ? "studied_desc" : "Studied";
                ViewBag.LeftParm = sortOrder == "Left" ? "left_desc" : "Left";
                switch (sortOrder)
                {
                    case "name_desc":
                        modules = modules.OrderByDescending(s => s.ModuleCode);
                        break;
                    case "Self":
                        modules = modules.OrderBy(s => s.SelfStudyHours);
                        break;
                    case "self_desc":
                        modules = modules.OrderByDescending(s => s.SelfStudyHours);
                        break;
                    case "Studied":
                        modules = modules.OrderBy(s => s.HoursStudied);
                        break;
                    case "studied_desc":
                        modules = modules.OrderByDescending(s => s.HoursStudied);
                        break;
                    case "Left":
                        modules = modules.OrderBy(s => s.HoursLeft);
                        break;
                    case "left_desc":
                        modules = modules.OrderByDescending(s => s.HoursLeft);
                        break;
                    default:  
                        modules = modules.OrderBy(s => s.ModuleCode);
                        break;
                }
                ViewData["HoursLeft"] = modules;
                return View();
            }


        }
    }
}

POE/Controllers/UserSemestersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DbManagement.Models;
using Modules;

namespace POE.Controllers
{
    public class UserSemestersController : Controller
    {
        private readonly Prog6212P2Context _context;

        public UserSemestersController(Prog6212P2Context context)
        {
            _context = context;
        }

        // GET: UserSemesters
        public async Task<IActionResult> Index()
        {
            int userID = HttpContext.Session.GetInt32("UserID").Value;
            ViewData["UserID"] = userID;
            return View();
        }        

        // GET: UserSemesters/Create
        public IActionResult Create()
        {
            int userID = HttpContext.Session.GetInt32("UserID").Value;
            ViewData["UserID"] = userID;
            return View();
        }

        // POST: UserSemesters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SemesterStartDate,WeeksInSemester")] UserSemester userSemester)
        {
            int userID = HttpContext.Session.GetInt32("UserID").Value;
            ViewData["UserID"] = userID;
            if (ModelState.IsValid)
            {
                SemesterManagement semester = new SemesterManagement();
                userSemester.UserId = userID;
                //if the semester exists, update the module
                if (semester.SemesterExists(userID))
                {
                    await semester.UpdateSemester(userID, userSemester.SemesterStartDate, userSemester.WeeksInSemester);
                }
                else
                {
                    //otherwise, add the semester
                    await semester.AddSemester(userSemester);
                }

                //Redirect to home page
                return RedirectToAction("Create", "Modules");
            }           
            return View();
        }

        

        
    }
}

POE/Views/Modules/Create.cshtml
@model DbManagement.Models.Module

@{
    ViewData["Title"] = "Create";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>


<h1>Add Modules</h1>

<h4>Module Information</h4>
<h6 style="color:#8C52FF;">Note: You may only add up to 6 modules.</h6>
<hr/>
<div class="row" >
    <div class="col-md-4">
        <form asp-action="Create" id="modFrm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>               
            <div class="form-group">
                <label asp-for="ModuleCode" class="control-label">Module Code</label>
                <input id="moduleCode" required asp-for="ModuleCode"  class="form-control" />
                <span id="modCode" asp-validation-for="ModuleCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModuleName" class="control-label">Module Name</label>
                <input id="moduleName" required asp-for="ModuleName" class="form-control" />
                <span id="modName" asp-validation-for="ModuleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credits" class="control-label"></label>
                <input id="moduleCredits" required asp-for="Credits" type="number" min="8" max="15" class="form-control" />
                <span id="modCredits"  asp-validation-for="Credits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassHours" class="control-label">Class Hours</label>
                <input id="moduleHours" required asp-for="ClassHours" type="number" min="2" max="6" class="form-control" />
                <span id="hours" asp-validation-for="ClassHours" class="text-danger"></span>
            </div>        
            <div style="display:flex;">
                <div class="form-group" >
                    <input id="addModule" type="submit" value="Add Module" class="submit-btns" />
                </div>
                <div  >
                    <input id="toHome" type="submit" value="To Home" class="submit-btns" style="margin-left:15px;" />
                </div>
            </div>
            
        </form>
    </div>
    <div id="listMods" class="col-md-6" style="margin-left: 10rem;height: 300px;margin-top: 30px;">
        <h4 style="color:#8C52FF;">Modules Added:</h4>
         <ol type="1" style="padding-left:1rem;">
                @foreach (var module in ViewBag.lstModules)
                {
                    <li>@module</li>
                }          
        </ol>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

POE/Views/Modules/Delete.cshtml
@model DbManagement.ModuleHtmlModule

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr/>
    <dl class="row">
        <dt class = "col-sm-2">
            Module Code
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModuleCode)
        </dd>
        <dt class = "col-sm-2">
            Module Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModuleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Credits)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Credits)
        </dd>
        <dt class = "col-sm-2">
            Class Hours
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassHours)
        </dd>
        <dt class = "col-sm-2">
            Self Study Hours
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SelfStudyHours)
        </dd>
    </dl>
    
    <h6 style="color: #8C52FF">All related study sessions and future study sessions will also be deleted.</h6>
    <form asp-action="Delete">
        <input type="hidden" asp-for="ModuleId" />
        <input type="submit" value="Delete" class="submit-btns" /> |
        <a asp-action="Details" class="delete-links">Back to List</a>
    </form>
</div>

POE/Views/Modules/Details.cshtml
@model DbManagement.ModuleHtmlModule
@{
    ViewData["Title"] = "Details";
}

<h1>All modules</h1>
<hr/>
<table class="table">
    <thead>
        <tr>
            <th>
                Module Code
            </th>
            <th>
                Module Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Credits)
            </th>
            <th>
                Class Hours
            </th>
            <th>
                Self Study Hours
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var module in ViewBag.ModuleData)
        {
            <tr>
                <td >
                    @module.ModuleCode
                </td>
                <td>
                    @module.ModuleName
                </td>
                <td>
                    @module.Credits
                </td>
                <td>
                    @module.ClassHours
                </td>
                <td>
                    @module.SelfStudyHours
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@module.ModuleId" class="delete-links">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

POE/Views/Modules/Index.cshtml
@model IEnumerable<DbManagement.Models.Module>

@{
    ViewData["Title"] = "Index";
}

<!doctype html>
<html lang="ar">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/album-rtl/">
    <link href="css/bootstrap.rtl.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
</head>
<body>
    <main>
        <div id="reminder" style="background-color:#8C52FF; color:white; height:2rem; border-radius:30px;">
            <p style="padding-top: 3px;font-weight:bold; text-align:center; ">@ViewBag.Reminder</p>
        </div>
        <div class="album py-5" style="padding-top:1.5rem">
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    <div class="col">
                        <div class="card">
                            <img id="home-img" class="bd-placeholder-img card-img-top" width="100%" height="225" src="~/images/read.png" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <a id="home-btns" asp-controller="Modules" asp-action="Create">
                                <input type="submit" value="Add Modules" class="submit-btns home-btn" />
                            </a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card ">
                            <img id="home-img" class="bd-placeholder-img card-img-top" width="100%" height="225" src="~/images/scrum.png" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <a id="home-btns" asp-controller="Modules" asp-action="Details">
                                <input type="submit" value="View Modules" class="submit-btns home-btn" />
                            </a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card ">
                            <img id="home-img" class="bd-placeholder-img card-img-top" width="100%" height="225" src="~/images/read_couch.png" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <a id="home-btns" asp-controller="StudySessions" asp-action="Create">
                                <input type="submit" value="Log Study Session" class="submit-btns home-btn" />
                            </a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card ">
                            <img id="home-img" class="bd-placeholder-img card-img-top" width="100%" height="225" src="~/images/book_ladder.png" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <a id="home-btns" asp-controller="StudySessions" asp-action="SessionsRequired">
                                <input type="submit" value="Study Sessions Required" class="submit-btns home-btn" />
                            </a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card ">
                            <img id="home-img" class="bd-placeholder-img card-img-top" width="100%" height="225" src="~/images/brainstorm.png" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <a id="home-btns" asp-controller="StudySessions" asp-action="Index">
                                <input type="submit" value="Study Sessions" class="submit-btns home-btn" />
                            </a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card ">
                            <img id="home-img" class="bd-placeholder-img card-img-top" width="100%" height="225" src="~/images/online.png" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <a id="home-btns" asp-controller="FutureStudySessions" asp-action="Create">
                                <input type="submit" value="Remind Me To Study" class="submit-btns home-btn" />
                                </a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card ">
                            <img id="home-img" class="bd-placeholder-img card-img-top" width="100%" height="225" src="~/images/bookshelf.png" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <a id="home-btns" asp-controller="FutureStudySessions" asp-action="Index">
                                <input type="submit" value="All Future Study Sessions" class="submit-btns home-btn" />
                                </a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card ">
                            <img id="home-img" class="bd-placeholder-img card-img-top" width="100%" height="225" src="~/images/learn.png" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <a id="home-btns" asp-controller="UserSemesters" asp-action="Create">
                                <input type="submit" value="Edit Semester Details" class="submit-btns home-btn" />
                            </a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card ">
                            <img id="home-img" class="bd-placeholder-img card-img-top" width="100%" height="225" src="~/images/read_couch.png" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <a id="home-btns" asp-controller="Graph" asp-action="Index">
                                <input type="submit" value="Study Statistics" class="submit-btns home-btn" />
                                </a>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>

    </main>

    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

POE/Views/Modules/ModuleLimit.cshtml
@model DbManagement.Models.Module
@{
    ViewData["Title"] = "NoModules";
}

<div style="margin-top:25px;">
    <h1>Module limit reached.</h1>
    <h4>You can only add 6 modules.</h4>

    <input id="modLimit" type="submit" value="Back To Home" class="submit-btns" style="margin-top:15px; width:15%" />
</div>

POE/Views/Modules/NoModules.cshtml
@model DbManagement.Models.Module
@{
    ViewData["Title"] = "NoModules";
}

<div style="margin-top:25px;">
    <h1>No Modules Added</h1>

    <input id="toHomeMods" type="submit" value="Back To Home" class="submit-btns" style="margin-top:15px; width:15%" />
</div>